/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Can({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../public/can3.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -0.03, 0.01]} rotation={[1.57, 0, 0.85]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('../../public/can3.gltf')
