/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Random({ ...props }) {

  const group = useRef();
  const { nodes, materials } = useGLTF('../assets/random4.gltf');
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Cube.geometry} material={materials.Material}/>
    </group>
  )}

useGLTF.preload('../assets/random4.gltf');
