/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/cat.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -0.03, 0.01]} rotation={[1.57, 0, 0.85]}>
        <mesh geometry={nodes.Cube001_1.geometry} material={nodes.Cube001_1.material} />
        <mesh geometry={nodes.Cube001_2.geometry} material={nodes.Cube001_2.material} />
      </group>
      <group position={[0, -0.03, -7.19]} rotation={[1.57, 0, 2.05]}>
        <mesh geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} />
        <mesh geometry={nodes.Cube006_1.geometry} material={nodes.Cube006_1.material} />
      </group>
      <mesh
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[0, -0.03, 0.01]}
        rotation={[3.14, 0, 0]}
        scale={21.19}
      />
    </group>
  )
}

useGLTF.preload('/cat.gltf')
